//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MegaCastingWPF.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MegaCastingEntities : DbContext
    {
        public MegaCastingEntities()
            : base("name=MegaCastingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<T_E_ADRESSE_ADR> T_E_ADRESSE_ADR { get; set; }
        public virtual DbSet<T_E_CONTACT_CTC> T_E_CONTACT_CTC { get; set; }
        public virtual DbSet<T_E_CONTENU_EDITORIAL_EDI> T_E_CONTENU_EDITORIAL_EDI { get; set; }
        public virtual DbSet<T_E_OFFRE_CASTING_CAST> T_E_OFFRE_CASTING_CAST { get; set; }
        public virtual DbSet<T_E_PROSPECT_PRO> T_E_PROSPECT_PRO { get; set; }
        public virtual DbSet<T_H_CLIENT_CLI> T_H_CLIENT_CLI { get; set; }
        public virtual DbSet<T_H_PARTENAIRES_PAR> T_H_PARTENAIRES_PAR { get; set; }
        public virtual DbSet<T_R_CONTENU_EDITORIAL_TYPE_CET> T_R_CONTENU_EDITORIAL_TYPE_CET { get; set; }
        public virtual DbSet<T_R_CONTRAT_CON> T_R_CONTRAT_CON { get; set; }
        public virtual DbSet<T_R_DOMAINE_METIER_DOM> T_R_DOMAINE_METIER_DOM { get; set; }
        public virtual DbSet<T_R_LOCALISATION_LOC> T_R_LOCALISATION_LOC { get; set; }
        public virtual DbSet<T_R_METIER_MET> T_R_METIER_MET { get; set; }
        public virtual DbSet<T_R_STATUT_JURIDIQUE_JUR> T_R_STATUT_JURIDIQUE_JUR { get; set; }
        public virtual DbSet<T_S_DATABASE_ADMIN_DBA> T_S_DATABASE_ADMIN_DBA { get; set; }
        public virtual DbSet<T_S_UTILISATEUR_UTI> T_S_UTILISATEUR_UTI { get; set; }
        public virtual DbSet<T_X_CODE_POSTAL_CPT> T_X_CODE_POSTAL_CPT { get; set; }
        public virtual DbSet<T_S_DATABASE_INFO_DBI> T_S_DATABASE_INFO_DBI { get; set; }
    }
}
