//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MegaCastingWPF.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_E_OFFRE_CASTING_CAST
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_E_OFFRE_CASTING_CAST()
        {
            this.T_R_CONTRAT_CON = new HashSet<T_R_CONTRAT_CON>();
            this.T_R_LOCALISATION_LOC = new HashSet<T_R_LOCALISATION_LOC>();
        }
    
        public int CAST_ID { get; set; }
        public string CAST_INTITULE { get; set; }
        public string CAST_REFERENCE { get; set; }
        public System.DateTime CAST_DATE_DEBUT_PUBLICATION { get; set; }
        public System.TimeSpan CAST_DUREE_DIFFUSION { get; set; }
        public System.DateTime CAST_DATE_DEBUT_CONTRAT { get; set; }
        public int CAST_NBR_POSTE { get; set; }
        public string CAST_DESCRIPTION_POSTE { get; set; }
        public string CAST_DESCRIPTION_PROFIL { get; set; }
        public int PRO_ID { get; set; }
        public int MET_ID { get; set; }
    
        public virtual T_H_CLIENT_CLI T_H_CLIENT_CLI { get; set; }
        public virtual T_R_METIER_MET T_R_METIER_MET { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_R_CONTRAT_CON> T_R_CONTRAT_CON { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_R_LOCALISATION_LOC> T_R_LOCALISATION_LOC { get; set; }
    }
}
