//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MegaCastingWPF.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_E_ADRESSE_ADR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_E_ADRESSE_ADR()
        {
            this.T_H_CLIENT_CLI = new HashSet<T_H_CLIENT_CLI>();
        }
    
        public int ADR_ID { get; set; }
        public string ADR_NUM_VOIE { get; set; }
        public string ADR_LIBELLE_RUE { get; set; }
        public string ADR_VILLE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_H_CLIENT_CLI> T_H_CLIENT_CLI { get; set; }
    }
}
