//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MegaCastingWPF.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_E_PROSPECT_PRO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_E_PROSPECT_PRO()
        {
            this.T_E_CONTACT_CTC = new HashSet<T_E_CONTACT_CTC>();
        }
    
        public int PRO_ID { get; set; }
        public string PRO_NAME { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_E_CONTACT_CTC> T_E_CONTACT_CTC { get; set; }
        public virtual T_H_CLIENT_CLI T_H_CLIENT_CLI { get; set; }
        public virtual T_H_PARTENAIRES_PAR T_H_PARTENAIRES_PAR { get; set; }
    }
}
