//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MegaCastingWPF.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_H_CLIENT_CLI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_H_CLIENT_CLI()
        {
            this.T_E_OFFRE_CASTING_CAST = new HashSet<T_E_OFFRE_CASTING_CAST>();
        }
    
        public int PRO_ID { get; set; }
        public Nullable<int> CLI_SIRET { get; set; }
        public Nullable<int> CLI_RNA { get; set; }
        public int JUR_ID { get; set; }
        public int ADR_ID { get; set; }
    
        public virtual T_E_ADRESSE_ADR T_E_ADRESSE_ADR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_E_OFFRE_CASTING_CAST> T_E_OFFRE_CASTING_CAST { get; set; }
        public virtual T_E_PROSPECT_PRO T_E_PROSPECT_PRO { get; set; }
        public virtual T_R_STATUT_JURIDIQUE_JUR T_R_STATUT_JURIDIQUE_JUR { get; set; }
    }
}
