//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MegaCastingWPF.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_R_CONTENU_EDITORIAL_TYPE_CET
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_R_CONTENU_EDITORIAL_TYPE_CET()
        {
            this.T_E_CONTENU_EDITORIAL_EDI = new HashSet<T_E_CONTENU_EDITORIAL_EDI>();
        }
    
        public int CET_ID { get; set; }
        public string CET_LIBELLE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_E_CONTENU_EDITORIAL_EDI> T_E_CONTENU_EDITORIAL_EDI { get; set; }
    }
}
