//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MegaCastingWPF.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_R_METIER_MET
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_R_METIER_MET()
        {
            this.T_E_OFFRE_CASTING_CAST = new HashSet<T_E_OFFRE_CASTING_CAST>();
        }
    
        public int MET_ID { get; set; }
        public string MET_LIBELLE { get; set; }
        public int DOM_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_E_OFFRE_CASTING_CAST> T_E_OFFRE_CASTING_CAST { get; set; }
        public virtual T_R_DOMAINE_METIER_DOM T_R_DOMAINE_METIER_DOM { get; set; }
    }
}
