//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MegaCastingWPF.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_S_DATABASE_ADMIN_DBA
    {
        public int DBA_ID { get; set; }
        public System.DateTime DBA_DATEHEURE { get; set; }
        public string DBA_NOM { get; set; }
        public string DBA_NATURE { get; set; }
        public string DBA_COMMANDE { get; set; }
    }
}
