//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MegaCastingWPF.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_S_UTILISATEUR_UTI
    {
        public int UTI_ID { get; set; }
        public string UTI_NOM { get; set; }
        public string UTI_PRENOM { get; set; }
        public string UTI_LOGIN { get; set; }
        public string UTI_MDP { get; set; }
        public bool UTI_ADMINISTRATEUR { get; set; }
    }
}
