//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MegaCastingWPF.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_X_CODE_POSTAL_CPT
    {
        public int CPT_ID { get; set; }
        public string CPT_CODE_POSTAL { get; set; }
        public string CPT_VILLE { get; set; }
    }
}
